# -*- coding: utf-8 -*-
"""imc.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13dNZeq2A3_gAx8ZqdmWcbrGqGqFKtJcP
"""

import pandas as pd
caminho = "/content/drive/MyDrive/Ciência de Dados/pessoas.xlsx"

arquivo = pd.read_excel(caminho)

tamanho = len(arquivo)
soma = 0

#Media de idade
for indice in range(tamanho):

  pessoa = arquivo.iloc[indice]
  N1 = pessoa['Idade']
  soma = soma + N1

media = soma/tamanho

print('Media de Idade:', media)


#Buscando o menos Peso
MenorPeso = None
nome_peso = None

for indice in range(tamanho):
    pessoa = arquivo.iloc[indice]
    peso = pessoa['Peso']
    nome = pessoa['Nome']

    if MenorPeso is None or peso < MenorPeso:
        MenorPeso = peso
        nome_peso = nome

print(f'O menor peso é: {MenorPeso} e pertence a {nome_peso}')


#Buscando a maior Altura
MaiorAltura = None
nome_altura = None

for indice in range(tamanho):
    pessoa = arquivo.iloc[indice]
    altura = pessoa['Altura']
    nome = pessoa['Nome']

    if MaiorAltura is None or altura > MaiorAltura:
        MaiorAltura = altura
        nome_altura = nome

print(f'A maior altura é: {MaiorAltura} e pertence a {nome_altura}')

#Adicionando a coluna IMC
IMC = []

for indice in range(tamanho):

  pessoa = arquivo.iloc[indice]
  imc = (pessoa['Peso'] / pessoa['Altura'])
  IMC.append(imc)

arquivo['IMC'] = IMC
arquivo.IMC

arquivo.to_excel('/content/drive/MyDrive/Ciência de Dados/pessoas.xlsx')


#Definido Grupo Dominante
tamanho = len(arquivo)
contagem_imc = {
    'Abaixo do peso': 0,
    'Peso normal': 0,
    'Sobrepeso': 0,
    'Obesidade': 0
}

for indice in range(tamanho):
    pessoa = arquivo.iloc[indice]
    imc = pessoa['IMC']

    if imc < 18.5:
        contagem_imc['Abaixo do peso'] += 1
    elif imc < 25.0:
        contagem_imc['Peso normal'] += 1
    elif imc < 30.0:
        contagem_imc['Sobrepeso'] += 1
    else:
        contagem_imc['Obesidade'] += 1

grupo_dominante = None
maior_quantidade = 0

for grupo, quantidade in contagem_imc.items():
    if quantidade > maior_quantidade:
        maior_quantidade = quantidade
        grupo_dominante = grupo

print(f"O grupo de IMC dominante é: '{grupo_dominante}' com {maior_quantidade} pessoas.")